# 仅当 hpa.enabled 为 true 时，才创建 HPA 资源
{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "my-app-bluegreen.fullname" . }}  # 资源名：应用名-环境（如 my-business-app-green）
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-app-bluegreen.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "my-app-bluegreen.fullname" . }}  # 关联对应环境的 Deployment
  minReplicas: {{ .Values.hpa.minReplicas }}  # 最小副本数（Pipeline 可覆盖）
  maxReplicas: {{ .Values.hpa.maxReplicas }}  # 最大副本数（Pipeline 可覆盖）
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.cpuTargetUtilization }}  # CPU 目标使用率（Pipeline 可覆盖）
